GET http://localhost:8080/principal
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJHA1NVZRRjMuZnJ3bjlXMVAxSU1WQU8zUE5TVDNUV0ZNZVE4LjBNcTc4VDNSbE5OYmtNRXo2IiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNTQzMzEyNCwidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.DpvjZpRHYrtX0po0Vb5EBCr8txzwvcKdb25hZnjPIzk

###

PUT http://localhost:8080/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJHA1NVZRRjMuZnJ3bjlXMVAxSU1WQU8zUE5TVDNUV0ZNZVE4LjBNcTc4VDNSbE5OYmtNRXo2IiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNTQzMzEyNCwidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.DpvjZpRHYrtX0po0Vb5EBCr8txzwvcKdb25hZnjPIzk

{
  "first_name": "John",
  "last_name": "John"
}

###

GET http://localhost:8080/users/1c4080ee-62be-4fb9-8470-78bf253996bd
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJHA1NVZRRjMuZnJ3bjlXMVAxSU1WQU8zUE5TVDNUV0ZNZVE4LjBNcTc4VDNSbE5OYmtNRXo2IiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNTQzMzEyNCwidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.DpvjZpRHYrtX0po0Vb5EBCr8txzwvcKdb25hZnjPIzk

###


GET http://localhost:8080/users
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJHA1NVZRRjMuZnJ3bjlXMVAxSU1WQU8zUE5TVDNUV0ZNZVE4LjBNcTc4VDNSbE5OYmtNRXo2IiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNTQzMzEyNCwidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.DpvjZpRHYrtX0po0Vb5EBCr8txzwvcKdb25hZnjPIzk

###
