POST http://localhost:8080/chat
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJFVWNzJvUkp4WVBlc2tNUW5HSDlDenVKSEdaVlZmR2JsSXhqazZGLkVsdnpZay9LdFB1U1BDIiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNjE5ODM0NywidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.Z7SpPNKyTnT-NaPTFgAyBP0fGogscxLbKLg7rPQWOHg

{
  "users": [
    "8c45861f-6d08-45e3-bb22-5f342d04ba70",
    "70e973dd-ec23-4493-afc0-57028e7d8258"
  ]
}

###

GET http://localhost:8080/chat
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJFVWNzJvUkp4WVBlc2tNUW5HSDlDenVKSEdaVlZmR2JsSXhqazZGLkVsdnpZay9LdFB1U1BDIiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNjE5ODM0NywidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.Z7SpPNKyTnT-NaPTFgAyBP0fGogscxLbKLg7rPQWOHg

###

GET http://localhost:8080/chat/c047952e-280f-4aec-8327-eeac103f9499
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJHA1NVZRRjMuZnJ3bjlXMVAxSU1WQU8zUE5TVDNUV0ZNZVE4LjBNcTc4VDNSbE5OYmtNRXo2IiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNTQ1NzE3NSwidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.YruIH1HjGIDy4DH6ImRxkZ3cDFycFPCMwFj9ncoVbfU

###

GET http://localhost:8080/chat/for
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsInBhc3N3b3JkIjoiJDJhJDEwJFVWNzJvUkp4WVBlc2tNUW5HSDlDenVKSEdaVlZmR2JsSXhqazZGLkVsdnpZay9LdFB1U1BDIiwiaXNzIjoiaHR0cHM6Ly9qd3QtcHJvdmlkZXItZG9tYWluLyIsImV4cCI6MTYwNjE5ODM0NywidXNlcm5hbWUiOiJpb25AaW9uLmNvbSJ9.Z7SpPNKyTnT-NaPTFgAyBP0fGogscxLbKLg7rPQWOHg

[
  "8c45861f-6d08-45e3-bb22-5f342d04ba70"
]